version: "3.4"
services:
  backend:
    build: ./
    ports:
      - "3000:3000"
    depends_on:
      - psql
    links:
      - psql
  psql:
    image: "postgres:11"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: game-juridico
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    restart: always
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
